-- Generated by tools/build_voiced_lines.py from BroadcastText 1.60.1.69913.
-- Hashes of NPC chat lines Blizzard has voiced. Do not edit; regenerate.
SpeakStone_VoicedLinesLocale = "enUS"
SpeakStone_VoicedLines = {
[436899743]=1,
[454368788]=1,
[1179033213]=1,
[1649763065]=1,
[1675327096]=1,
[2093453389]=1,
[2148481041]=1,
[2451450220]=1,
[2819347615]=1,
[3153519780]=1,
[3336230373]=1,
[3382207401]=1,
}
